# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    network_mode: host 
    restart: always
    volumes:
      - /opt/mosquitto/config:/mosquitto/config
      - /opt/mosquitto/data:/mosquitto/data
      - /opt/mosquitto/log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"

  mqttclient:
    image: "mqtt-client:latest"
    build:
      context: .
      dockerfile: /Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5000:80
      - 5001:443
    restart: always