# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    network_mode: host 
    restart: always
    volumes:
      - C:\Appl\MQTT\config:/mosquitto/config
      - C:\Appl\MQTT\data:/mosquitto/data
      - C:\Appl\MQTT\log:/mosquitto/log
    ports:
      - "1883:1883"
      - "9001:9001"
  mqttclient:
    image: mqttclient
    build:
      context: .
      dockerfile: MQTT_Client/Dockerfile
