name: publish

on: [push]

jobs:
  publish-MQTT_Client-Image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/m-wolfer/mqtt_client
